### ISSUE TITLE
Fix blue dots and underlines below the Font Awesome icons in the footer

### ISSUE THREAD

**Issue by arnoldboy123** [arnoldboy123/arnoldboy123.github.io#11]
Currently because the font awesome icons at the bottom are links, there are blue underline and dots underneath.

I would like to remove them.

**Comment by richard-G** [comment]
Couple ways to fix this, it's the `paper.css` which is defining your a tags to have the underline as a background image - so either you can:

- Add an inline style to each a tag in your footer with `background-image: none`, eg:

```html
<a href="https://twitter.com/_Arnoldho" style="background-image: none;"><i class="fab fa-twitter"></i></a>
```

Or
 
- Add a rule to your CSS which will take precedence for a tags within your footer:
```css
footer a {
    background-image: none;
}

**Comment by arnoldboy123** [comment]
Fixed it using the latter method, thanks!
