### ISSUE TITLE
Fix links

### ISSUE THREAD

**Issue by arnoldboy123** [arnoldboy123/arnoldboy123.github.io#13]
Some links on the page are dead because I forgot to add the prefix https:// which meant that the html code thinks I am trying to find the link from within my repo.

I need to fix these links.

**Comment by Avila5301** [comment]
Hi, I would like to work on this issue for you.

**Comment by Avila5301** [comment]
Hi, I just wanted to say, great personal site. I think you're on the right path. One thing I notice was some links had quotes and others did not. I replaced all the links without " " after each href. Also, noticed some inline style but I think the markup was just a bit off. I think you were trying to do style="text:center" but your css had a class already built to center text which was .text-center or in html class="text-center". Anyways, hope you continue your learning path and looking forward to more of your content. Happy Coding.

**Comment by arnoldboy123** [comment]
Thanks Avila! Really appreciate your feedback, this is the first site I built and I took a pre-made CSS style sheet from paperCSS, for learning I probably should look at the CSS file a bit more :) Feel free to do a Pull Request whenever on whatever issues you found as well!
Thanks so much :)
